# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: my-oci-pool


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: ls -l
  displayName: 'Display content of git checkout'

- script: set | grep -i TF_VAR
  displayName: Display TF Vars Test

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.3'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

